[package]
name = "w5500"
version = "0.1.0"
authors = ["Michael Watzko <michael@watzko.de>"]
repository = "https://git.tallbyte.com/rust/w5500.git"
description = "W5500 IoT Controller implementation. Currently UDP sending and receiving is working. WIP"
keywords = ["embedded", "w5500", "iot", "arm", "stm32"]
categories = ["embedded", "hardware-support", "no-std", "network-programming"]
license = "MIT"

[dependencies]
byteorder = { version = "1.2.1", default-features = false }
embedded-hal = "0.1.2"
nb = "0.1.1"